<?php
/*
 * Display the nav bar
 *
 * Since:	Feb 25, 2016
 * Author:	Constantin MASSON
 */
?>

<header id="site-header-wrap">
	<div id="site-header">
		<div id="site-header-title">
			Anne Grinda Masson
		</div>
		<nav id="site-header-navbar">
			<ul class="navbar-active">
				<li><a href="/index">Accueil</a></li>
				<li><a href="/gallery">Galerie</a></li>
				<li><a href="/aboutme">Qui suis-je?</a></li>
				<li><a href="/contact">Contact</a></li>
			</ul>
	
			<a class="toggle-navbar" href="#">&#9776;</a>
		</nav>
	</div>
</header>

