<?php
/*
 * Display the nav bar
 *
 * Since:	Feb 25, 2016
 * Author:	Constantin MASSON
 */
?>

<header id="site-header-wrap">
	<div id="site-header">
		<h1>Anne Grinda MASSON</h1>
		<nav>
			<ul>
				<li><a href="/index">Accueil</a></li>
				<li><a href="/gallery">Galerie</a></li>
				<li><a href="/aboutme">Qui suis-je?</a></li>
				<li><a href="/contact">Contact</a></li>
			</ul>
		</nav>
	</div>
</header>

