<?php
/*
 * Display the nav bar
 *
 * Since:	Feb 25, 2016
 * Author:	Constantin MASSON
 */
?>

<header id="site-header-wrap">
	<nav id="site-header" class="navbar">
		<div class="container-fluid">
			<div class="navbar-header">
				<div id="site-header-title">
					<a href="/index">Anne Grinda</a>
				</div>
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#site-header-navbar-collapse" aria-expanded="false">
					<span class="glyphicon glyphicon-align-justify"></span>
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>

			<div class="collapse navbar-collapse" id="site-header-navbar-collapse">
				<ul id="site-header-navbar" class="nav navbar-nav navbar-right">
					<li><a href="/index">Accueil</a></li>
					<li><a href="/gallery">Galerie</a></li>
					<li><a href="/aboutme">Qui suis-je?</a></li>
					<li><a href="/contact">Contact</a></li>
				</ul>
			</div>
		</div><!-- End Container-fluid -->
	</nav>
</header>
