<?php
/*
 * Display one Gallery
 *
 * DEV NOTE:
 * The path for img is just horribly done in the ugliest way possible but, 
 * I didn't have time for that. 
 * To update later (Soo, atm, keep the '../' because the URL rewriting create
 * an url /gallery/nb
 *
 * Since Feb 23, 2016
 */
require_once PATH_MODULES.'core/views/partials/header.phtml';
?>
<div class="page-header">
	<h1><?php echo $gallery->getName(); ?></h1>
</div>

<div class="container-fluid">
	<div class="row">
	<?php foreach ($gallery->getListImages() as $img): 

		//Check the dev note to understand this ugly '../'
		$imgPath = '../'.PATH_GALLERY.$gallery->getName().'/'.$img->getName().'.'.$img->getExtension();
		?>
		<div class="col-xs-4 col-md-3">
			<a href="<?php echo $imgPath; ?>" 
				class="thumbnail" 
				data-lightbox="<?php echo $gallery->getName();?>" 
				data-title="<?php echo $img->getName(); ?>"
			>
				<img src="<?php echo $imgPath?>" alt="<?php echo $imgPath?>">
			</a>
		</div>
	<?php endforeach; ?>
	</div>
</div><!-- End Fluid container -->

<script>
	lightbox.option({
		'resizeDuration': 200,
		'wrapAround': true
	})
</script>
