<?php
/*
 * Display all the Galleries
 *
 * Since Feb 22, 2016
 */

require_once PATH_MODULES.'core/views/partials/header.phtml';
?>


<div class="wrapper-general-content">

<?php if(empty($listGalleries)) :?>
	<p>No gallery</p>
<?php else : ?>
	<div class="container-fluid">
		<div class="row">
		<?php
		/*
		 * Note: the row can goes over the 12 size limite, the other
		 * elements will just be placed under. (See Bootstrap grid doc)
		 * It's not very nice but maybe better than creating a counter etc
		 */

		//Display each gallery
		foreach ($listGalleries as $gallery): 

			$link = $pathimg.'welcome/image1.jpg';
			if(!$gallery->isEmpty()){
				$img	= $gallery->getListImages()[0];
				$link	= $pathimg.'gallery/'.$gallery->getName().'/'.$img->getName().'.'.$img->getExtension();
			}

			?>
			<div class="col-xs-12 col-sm-6 col-md-4">
				<div class="thumbnail">
					<a href="/gallery/<?php echo $gallery->getId(); ?>">
					<img src="<?php echo $link;?>" alt="<?php echo $gallery->getName(); ?>">
					</a>
					<div class="caption">
						<h3><?php echo $gallery->getName();?></h3>
					</div>
				</div>
			</div>
		<?php endforeach; ?>
		</div><!-- End class row -->
	</div><!-- End container-fluid -->
<?php endif; ?>

</div><!-- End wrapper -->
