<?php
/*
 * Display all the Galleries
 *
 * Since Feb 22, 2016
 */

require_once PATH_MODULES.'core/views/partials/header.phtml';
?>

<h1>Galleries</h1>
<p>List galleries</p>

<?php if(empty($listGalleries)) :?>
	<p>No gallery</p>
<?php else : ?>
	<div class="container-fluid">
		<div class="row">
		<?php
		/*
		 * Note: the row can goes over the 12 size limite, the other
		 * elements will just be placed under. (See Bootstrap grid doc)
		 * It's not very nice but maybe better than creating a counter etc
		 */

		//Display each gallery
		foreach ($listGalleries as $gallery): 
			$links = $gallery->isEmpty() ? $pathimg.'welcome/image1.jpg' : $pathimg.'welcome/images1.jpg';
			?>
			<div class="col-xs-12 col-sm-6 col-md-4">
				<div class="thumbnail">
					<a href="/gallery/<?php echo $gallery->getId(); ?>">
					<img src="<?php echo $pathimg.'/welcome/image1.jpg';?>" alt="<?php echo $gallery->getName(); ?>">
					</a>
					<div class="caption">
						<h3><?php echo $gallery->getName();?></h3>
					</div>
				</div>
			</div>
		<?php endforeach; ?>
		</div>
<?php endif; ?>

</div>
