<?php 
/*
 *
 * Since:	Feb 27, 2016
 * Author:	Constantin MASSON
 */
require_once PATH_MODULES.'core/views/partials/header.phtml';
?>

<div class="wrapper-general-content">
	
	<div class="page-header">
		<h1>Qui suis-je</h1>
	</div>

	<div class="container">
		<div class="jumbotron">
			<div class="row">
				<div class="col-sm-3">
					<h1>J'aime...</h1>
					<ul>
						<li>Fixer l'éphémère</li>
						<li>Capter le mouvement</li>
						<li>Saisir une ambiance...</li>
					</ul>
				</div>
				<div class="col-sm-9 hidden-xs">
					<img src="/imgs/site/aboutme2.jpg" alt="about me" class="img-circle img-responsive">
				</div>
			</div>
			<p><strong>D'un coup de crayon!</strong></p>
		</div>
	</div>

	<div class="container">
		<div class="panel panel-default">
			<div class="panel-body text-center">
				<img src="/imgs/site/aboutme.jpg" alt="about me">
			</div>
		</div>
	</div>
</div>
