<?php 
/*
 *
 * Since:	Feb 27, 2016
 * Author:	Constantin MASSON
 */
require_once PATH_MODULES.'core/views/partials/header.phtml';
?>

<div class="wrapper-general-content">
	
	<div class="page-header">
		<h1>Qui suis-je</h1>
	</div>

	<div class="jumbotron">
		<div class="container">
			<h1>J'aime...</h1>
			<p>Fixer l'éphémère</br>
				Capter le mouvement</br>
				Saisir une ambiance...
			</p>
			<p>D'un coup de crayon!</p>
		</div>
	</div>


	<div class="panel panel-default">
		<div class="panel-body text-center">
			<img src="/imgs/site/aboutme.jpg" alt="about me">
		</div>
	</div>
</div>
