<?php 
/*
 * Contact Page
 *
 * Since:	Feb 27, 2016
 * Author:	Constantin MASSON
 */
require_once PATH_MODULES.'core/views/partials/header.phtml';
?>

<div class="wrapper-general-content">
	<div class="page-header">
		<h1>Me Contacter</h1>
	</div>

	<div class="jumbotron">
		<div class="container">
			<h1>Anne Grinda</h1>
			<h3>Illustratrice - Paris</h3>
			<p>+33 6 11 18 06 66</p>
			<a href="mailto:anne.grinda@sfr.fr">
				anne.grinda@sfr.fr
			</a>
			<p>SIRET 52103842200015</p>
			<img src="/imgs/site/contact.jpg" alt="about me" class="img-rounded img-responsive">
	  </div>
	</div>
</div>
