<?php
/*
 * Display the home page
 *
 * Since:	Feb 22, 2016
 * Author:	Constantin MASSON
 */
?>

<?php require_once dirname(__FILE__).'/partials/header.phtml'; ?>

<!-- Bootstrap Carousel -->
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="5000">
	<!-- Indicators -->
	<ol class="carousel-indicators">
		<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
		<li data-target="#carousel-example-generic" data-slide-to="1"></li>
	</ol>

	<!-- Wrapper for slides -->
	<div class="carousel-inner" role="listbox">
		<div class="item active">
			<img src="<?php echo $pathimg.'/site/welcome1.jpg';?>" alt="...">
		</div>
		<div class="item">
			<img src="<?php echo $pathimg.'site/welcome2.jpg';?>" alt="...">
		</div>
		<div class="item">
			<img src="<?php echo $pathimg.'site/welcome3.jpg';?>" alt="...">
		</div>
		<div class="item">
			<img src="<?php echo $pathimg.'site/welcome4.jpg';?>" alt="...">
		</div>
	</div>

	<!-- Controls -->
	<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
		<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
		<span class="sr-only">Previous</span>
	</a>
	<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
		<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
		<span class="sr-only">Next</span>
	</a>
</div>
