<!DOCTYPE html>
<?php $pageTitle = isset($pageTitle) ? $pageTitle : "Anne Grinda-Masson"; ?>
<html>
	<head>
		<title><?php echo "$pageTitle"; ?></title>
		<meta charset="utf-8">

		<!-- Bootstrap -->
		<link rel="stylesheet" type="text/css" href="<?php echo $pathcss.'bootstrap/bootstrap.min.css';?>"/>
		<script src="<?php echo $pathjs.'bootstrap/bootstrap.min.js';?>"></script>
		<meta http-equiv ="X-UA-Compatible" content = "IE = edge">
		<meta name = "viewport" content = "width = device-width, initial-scale = 1">

		<!-- HTML5 shim and respond.js IE8 support for HTML5 -->
		<!--[if lt IE 9]>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>

	<body>
		<div id="main-wrapper">
			<?php echo "$content"; ?>
		</div>
	</body>
</html>
