<!DOCTYPE html>
<?php $pageTitle = isset($pageTitle) ? $pageTitle : "Anne Grinda-Masson"; ?>
<html>
	<head>
		<title><?php echo "$pageTitle"; ?></title>
		<meta charset="utf-8">

		<!-- General CSS -->
		<link rel="stylesheet" type="text/css" href="<?php echo $pathcss.'general.css';?>"/>
		<link rel="stylesheet" type="text/css" href="<?php echo $pathcss.'header.css';?>"/>
		<script src = "/js/jquery-2.2.1.min.js"> </script>

		<!-- Bootstrap -->
		<link rel="stylesheet" type="text/css" href="/bootstrap/css/bootstrap.min.css"/>
		<link rel="stylesheet" type="text/css" href="/bootstrap/css/bootstrap-theme.min.css"/>
		<meta http-equiv ="X-UA-Compatible" content = "IE = edge">
		<meta name = "viewport" content = "width = device-width, initial-scale = 1">
		<script src="/bootstrap/js/bootstrap.min.js"></script>

		<!-- Lightbox 2 -->
		<link rel="stylesheet" type="text/css" href="/lightbox2/css/lightbox.css"/>

		<!-- HTML5 shim and respond.js IE8 support for HTML5 -->
		<!--[if lt IE 9]>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>

	<body>
		<div id="main-wrapper">
			<?php echo "$content"; ?>
		</div>

		<!-- Script (JQuery/Bootstrap/lightbox) -->
		<script src="/lightbox2/js/lightbox.js"></script>

	</body>
</html>
